let myNumber = 5, myOtherNumber = 5;
let myTotal = myNumber * myOtherNumber;

let myName = "";
let myCombo = "" + myNumber + myOtherNumber;
let myOtherCombo = myNumber + myOtherNumber;
let myRemainder = myNumber % 5;
let i = 2;
let int = 4;
let myBoolean = false;
console.log("myNumber is type: " + typeof myNumber + " and value: " + myNumber);
console.log("myOtherNumber is type: " + typeof myOtherNumber + " and value: " + myOtherNumber);
console.log("myTotal is type: " + typeof myTotal + " and value: " + myTotal);
console.log("myName is type: " + typeof myName + " and value: " + myName);
console.log("myCombo is type: " + typeof myCombo + " and value: " + myCombo);
console.log("myOtherCombo is type: " + typeof myOtherCombo + " and value: " + myOtherCombo);
console.log("myRemainder is type: " + typeof myRemainder + " and value: " + myRemainder);
console.log("i is type: " + typeof i + " and value: " + i);
console.log("int is type: " + typeof int + " and value: " + int);
console.log("myBoolean is type: " + typeof myBoolean + " and value: " + myBoolean);
